const config = {

    FETCH_ENDPOINT_URL: process.env.FETCH_ENDPOINT_URL,
    COMPOSE_INGESTION_URL: process.env.COMPOSE_INGESTION_URL,
    COMPOSE_PROJECT_ALIAS: process.env.COMPOSE_PROJECT_ALIAS,
    COMPOSE_ENVIRONMENT_ALIAS: process.env.COMPOSE_ENVIRONMENT_ALIAS,
    COMPOSE_COLLECTION_ALIAS: process.env.COMPOSE_COLLECTION_ALIAS,
    COMPOSE_CLIENT_ID: process.env.COMPOSE_CLIENT_ID,
    COMPOSE_CLIENT_SECRET: process.env.COMPOSE_CLIENT_SECRET,
    COMPOSE_MANAGEMENT_URL: process.env.COMPOSE_MANAGEMENT_URL,

};

export default config;